name: movie_tickets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  #UI
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.17

  #firebase
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.5
  firebase_ai: ^2.0.0
  flutter_chat_ui: ^1.6.15

  #bloc
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  #servies
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.0
  share_plus: ^11.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  get_it: ^8.0.3
  intl: ^0.19.0

  #inject code
  injector: ^4.0.0
  injectable: ^2.5.0
  injectable_generator: ^2.6.2

  #local storageP
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.2
  
  #object builder
  freezed: ^2.5.3
  freezed_annotation: ^2.4.4
  
  #payment
  youtube_player_flutter: ^9.1.1
  rxdart: ^0.28.0
  dotted_border: ^2.1.0
  google_maps_flutter: ^2.10.0
  shimmer: ^3.0.0
  go_router: ^14.8.1
  localization: ^2.1.1
  uuid: ^4.3.3
  crypto: ^3.0.6
  url_launcher: ^6.3.1
  webview_flutter: ^4.11.0
  flutter_stripe: ^11.0.0
  web_socket: ^1.0.1
  web_socket_channel: ^3.0.3
  dartz: ^0.10.1
  supabase_flutter: ^2.9.0
  mime: ^2.0.0
  pinput: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.otf
          weight: 600
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
          weight: 400

  assets:
    - assets/i18n/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/data/
    - assets/images/movie/
    - assets/images/events/
    - assets/images/plays/
    - assets/images/casts/
    - assets/images/cines/
