// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY_YSboB_yjdLzP0Iy4gZd_e3KdFYo_50',
    appId: '1:965619098215:web:30d8527eb2c01494722ac2',
    messagingSenderId: '965619098215',
    projectId: 'movie-tickets-40726',
    authDomain: 'movie-tickets-40726.firebaseapp.com',
    databaseURL: 'https://movie-tickets-40726-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movie-tickets-40726.firebasestorage.app',
    measurementId: 'G-7JWXY7WQGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8YU1hfe-lmvyHmjgxfjBIfR3dZsRQBR8',
    appId: '1:965619098215:android:7b5400d154d1552e722ac2',
    messagingSenderId: '965619098215',
    projectId: 'movie-tickets-40726',
    databaseURL: 'https://movie-tickets-40726-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movie-tickets-40726.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn4Zcykk4osk4qbuTKrlcqbbSe7nRP8t4',
    appId: '1:965619098215:ios:08f2bbe56f22443f722ac2',
    messagingSenderId: '965619098215',
    projectId: 'movie-tickets-40726',
    databaseURL: 'https://movie-tickets-40726-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movie-tickets-40726.firebasestorage.app',
    androidClientId: '965619098215-op1v6jkol9nmoj9bfq806kkpjtqk9qsu.apps.googleusercontent.com',
    iosClientId: '965619098215-47o5crrdear7gusijk2qs92s8c01mq43.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieTickets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn4Zcykk4osk4qbuTKrlcqbbSe7nRP8t4',
    appId: '1:965619098215:ios:08f2bbe56f22443f722ac2',
    messagingSenderId: '965619098215',
    projectId: 'movie-tickets-40726',
    databaseURL: 'https://movie-tickets-40726-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movie-tickets-40726.firebasestorage.app',
    androidClientId: '965619098215-op1v6jkol9nmoj9bfq806kkpjtqk9qsu.apps.googleusercontent.com',
    iosClientId: '965619098215-47o5crrdear7gusijk2qs92s8c01mq43.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieTickets',
  );
}
